### ISSUE TITLE
OTA update from L4T 32.3.1 to 32.4.3

### ISSUE THREAD

**Issue by gb-g** [OE4T/meta-mender-community#9]
I hope this is the right place to post this:
I'm using a TX2, and meta-tegra zeus-l4t-32.3.1 , meta-mender zeus-v2020.06 and u-boot.
I built an artifact using meta-tegra dunfell-l4t-32.4.3 and meta-mender dunfell-v2020.10
A Mender (managed, not standalone) update with this artifact is successful:
```
{"level":"info","message":"Collected output (stderr) while running script /var/lib/mender/scripts/ArtifactCommit_Leave_20_printVolatileInfo
nvbootctrl dump-slots-info:
slot: 0,             priority: 14,             suffix: _a,             retry_count: 7,             boot_successful: 0
slot: 1,             priority: 15,             suffix: _b,             retry_count: 7,             boot_successful: 1
nvbootctrl get-current-slot:1
mender_boot_part=33
---------- end of script output","timestamp":"2020-11-16T18:32:16Z"}
/dev/mmcblk0p33 is used
```
But after another reboot, it switches back to the old partition:
```
slot: 0,            priority: 13,            suffix: _a,            retry_count: 7,            boot_successful: 0
slot: 1,            priority: 15,            suffix: _b,            retry_count: 7,            boot_successful: 1
current-slot 1
/dev/mmcblk0p1 is used
mender_boot_part=1
```

**Comment by gb-g** [comment]
Another try with same setup:
State before update: (L4T 32.3.1)
```
slot: 0,             priority: 14,             suffix: _a,             retry_count: 7,             boot_successful: 1
slot: 1,             priority: 15,             suffix: _b,             retry_count: 7,             boot_successful: 1
nvbootctrl get-current-slot: 1
/dev/mmcblk0p33 is used
```
After successful update (with 32.4.3 artifact):
```
{"level":"info","message":"Collected output (stderr) while running script /var/lib/mender/scripts/ArtifactCommit_Leave_20_printVolatileInfo
nvbootctrl dump-slots-info:
slot: 0,             priority: 15,             suffix: _a,             retry_count: 6,             boot_successful: 0
slot: 1,             priority: 14,             suffix: _b,             retry_count: 7,             boot_successful: 1
nvbootctrl get-current-slot:0
mender_boot_part=1
---------- end of script output","timestamp":"2020-11-19T14:50:20Z"}
{"level":"info","message":"Collected output (stderr) while running script /var/lib/mender/scripts/ArtifactCommit_Leave_90_bl-commit
nvbootctrl get-current-slot 0
nvbootctrl mark-boot-successful
--------- end of script output","timestamp":"2020-11-19T14:50:20Z"}
/dev/mmcblk0p1 is used
```
After another reboot:
```
slot: 0,             priority: 14,             suffix: _a,             retry_count: 7,             boot_successful: 1
slot: 1,             priority: 14,             suffix: _b,             retry_count: 7,             boot_successful: 1
nvbootctrl get-current-slot: 0
/dev/mmcblk0p33 is used
mender_boot_part=33
```

**Comment by dwalkes** [comment]
@gb-g 

> A Mender (managed, not standalone) update with this artifact is successful:
> But after another reboot, it switches back to the old partition:

Have you verified the behavior with mender standalone already and is there a difference in behavior?

Have you tried to obtain the serial port boot logs to see why u-boot decides to roll back the boot part?

**Comment by gb-g** [comment]
So far I can confirm that mender standalone has the same behavior, rollback after second reboot.
[standalone.log](https://github.com/OE4T/meta-mender-community/files/5603770/standalone.log)

I noticed that this [statement](https://forums.developer.nvidia.com/t/mmcblk0boot1-usage-at-address-4177408-and-u-boot-parameter-storage-space-availability/82113/14), to have u-boot use the old 32.3.1 location, might entail a recalculation of CONFIG_ENV_SIZE, CONFIG_ENV_OFFSET, or CONFIG_ENV_OFFSET_REDUND .

**Comment by dwalkes** [comment]
> I noticed that this statement, to have u-boot use the old 32.3.1 location, might entail a recalculation of CONFIG_ENV_SIZE, CONFIG_ENV_OFFSET, or CONFIG_ENV_OFFSET_REDUND .

Those variables should be setup for the mender build [automagically using mender uboot patches](https://github.com/OE4T/meta-mender-community/blob/master/meta-mender-tegra/recipes-bsp/u-boot/patches/0010-tegra-mender-auto-configured-modified.patch) I believe, so I don't think the comment in the post applies to the mender implementation based on meta-mender-community.  The main thing I'm trying to figure out there is whether we really need to relocate the VER partition.  It doesn't look like we do based on the most recent comments.

The serial port logs and/or u-boot console debug are probably going to be the best way to figure this out.  See if you can modify variables from fw_setenv in linux and read them in u-boot and vise versa.

**Comment by mirzak** [comment]
Is U-boot updated in this case? 

It might be that if you update U-Boot and  `CONFIG_ENV_OFFSET` is changed in U-Boot, you need to make sure to update`/etc/fw_env.config` as well. By default `/etc/fw_env.config` is linked to `/data`, if this is the case on tegra as well, then it would explain this behaviour.

**Comment by dwalkes** [comment]
Thanks @mirzak 

> Is U-boot updated in this case?

Yes

> It might be that if you update U-Boot and CONFIG_ENV_OFFSET is changed in U-Boot

I don't believe we've changed the u-boot config CONFIG_ENV_OFFSET, or at least the intention was not to change it, now that we've got clarification it's not necessary based on latest update [here](https://forums.developer.nvidia.com/t/mmcblk0boot1-usage-at-address-4177408-and-u-boot-parameter-storage-space-availability/82113/16).  See the tab in [this sheet](https://docs.google.com/spreadsheets/d/14zVltS2LTwCNywoje6_8wzFzHQ3sYVhY6C7T0DkOnx0/edit#gid=0) at "TX2 L4T 32.3.1 + Mender U-boot support" compared to "jetson-tx2 - r32.4.3" where both are locating the mender version of the UBENV at 0x7BB000 (0x3BB0000 mmcblk0boot1 offset).

I agree this is something good to double check though, that all settings for uboot environment location are in agreement.

**Comment by gb-g** [comment]
> The serial port logs and/or u-boot console debug are probably going to be the best way to figure this out. 

I am looking for clues in those logs now.

> See if you can modify variables from fw_setenv in linux and read them in u-boot and vise versa.

That works.

**Comment by gb-g** [comment]
I guess U-Boot rolls back because of bootcount ([short log](https://github.com/OE4T/meta-mender-community/files/5630782/short.log)). I noticed that after `mender -commit`, the bootcount in fw_printenv is 1, but after rebooting, U-Boot warns that altbootcmd is used because the bootlimit (1) is exceeded, and bootcount is 2. (also, upgrade_available stays 1 after commit)
(I used #8 here, I had the problem with the roll back also without it).

**Comment by dwalkes** [comment]
@gb-g thanks for the trace, so if I understand correctly everything appears to be working as expected, it's just that `bootcount` isn't getting reset after update.

I think I need someone (maybe @mirzak ?) to enlighten me about how this is supposed to work.  I see the documentation [here](https://www.denx.de/wiki/DULG/UBootBootCountLimit) which describes how bootcount works, however I'm not seeing the logic I would expect regarding resetting bootcount after a normal boot in [mender client](https://github.com/mendersoftware/mender/search?q=bootcount) and I don't see relevant reverences in [libubootenv](https://github.com/sbabic/libubootenv/search?q=bootcount) or [linux-tegra](https://github.com/OE4T/linux-tegra-4.9/search?q=bootcount).  I also don't see the details about how this works in [the U-Boot integration section of mender documentation](https://docs.mender.io/system-updates-yocto-project/board-integration/bootloader-support/u-boot/manual-u-boot-integration#u-boot-features) and I'm coming up cold on mender hub, the closest I can find is [this comment](https://hub.mender.io/t/mender-rollback-reset-occurs-before-successful-rollback/283/9?u=dwalkes) which discusses in the context of criteria for commit and connection to the mender server.

**Comment by mirzak** [comment]
Running `mender -commit` should be the equivalent of running:

```
fw_setenv upgrade_available 0
```

I do not think that we clear `bootcount` in `mender -commit` but this should not have any impact as `bootcount` is only taken in to consideration if `upgrade_available=1`. So would focus on this variable instead.

> also, upgrade_available stays 1 after commit)

This hints that there is something wrong with U-Boot environment and the interaction between `fw_setenv` and U-Boot binary. After you run `mender -commit` this must be `upgrade_available=0` both when you run `fw_printenv upgrade_available` and if you do `printenv upgrade_available` in U-Boot.

Also for reference when you run `mender -install`, this would be the equivalent:

```
fw_setenv -s - <<EOF
mender_boot_part <number of new part to boot>
upgrade_available 1
bootcount 0
EOF
```

**Comment by gb-g** [comment]
I tried running `fw_setenv test_from_linux 1` and I can see it both in Linux and in U-Boot.
But right after I run `mender -commit` , running `fw_printenv upgrade_available` gives `upgrade_available=1` .
(I wonder if this somehow related to https://tracker.mender.io/projects/MEN/issues/MEN-3970 )

The relevant part of [short.log](https://github.com/OE4T/meta-mender-community/files/5630782/short.log) is:
```
jetson-tx2:~# mender -commit
...
INFO[0000] Mender running on partition: /dev/mmcblk0p33  module=cli
Committing Artifact...
...
INFO[0000] Collected output (stderr) while running script /var/lib/mender/scripts/ArtifactCommit_Enter_80_bl-check-update
+ LABELCHARS=AB
+ echo 'Verifying Tegra bootloader update'
++ nvbootctrl get-current-slot
+ curslot=1
+ cfglbl='"RootfsPartB"'
++ grep -h '"RootfsPartB":' /etc/mender/mender.conf /var/lib/mender/mender.conf
++ tr -d '" '
++ cut -d, -f1
++ cut -d: -f2
+ devnam=/dev/mmcblk0p33
+ '[' -z /dev/mmcblk0p33 ']'
+ '[' 0p33 '!=' /dev/mmcblk0p33 ']'
++ fw_printenv -n mender_boot_part
+ bootpart=33
+ '[' -z 33 ']'
++ expr 33 + 0
+ devnampart=33
+ '[' -z 33 ']'
+ '[' 33 -ne 33 ']'
+ exit 0

---------- end of script output  module=executor
...
INFO[0000] Committing update                             module=dual_rootfs_device
...
jetson-tx2:~# fw_printenv upgrade_available
upgrade_available=1
```

**Comment by mirzak** [comment]
Which Mender client version are you running?

> (I wonder if this somehow related to https://tracker.mender.io/projects/MEN/issues/MEN-3970 )

This could be the case, though the symptoms where different in that case. Variables would get unset (removed). But you are using U-Boot 2016.x, which would be a problematic version in regards to fw_setenv syntax, but again I would expect you to hit the problem earlier if that was the case. 

My understanding of meta-tegra/dunfell, is that it has switched to using upstream U-Boot and libubootenv as provider for fw_setenv/fw_getenv which you might be using. Can you verify the provider of these executable?

We have done a new release of the Mender client which fixes those problems mentioned in that ticket (2.4.1/2.3.1), which are part of the latest revision of dunfell. You could test with those, but do not think it is related.

Also can you check if there are multiple `fw_setenv` in your system:

```
find / -name fw_setenv
```

Also does this work:

```
fw_setenv test_variable=1
```

**Comment by gb-g** [comment]
I tested now with Mender client version is 2.4.1 (I had a problem with roll back after second reboot also with 2.2.1 and 2.4.0).
U-Boot is updated here from 2016.07 before Mender update to 2020.04 after Mender update.
Used sources are https://github.com/OE4T/u-boot-tegra/tree/patches-v2020.04 and https://github.com/sbabic/libubootenv f4b9cde, which provides fw_setenv/fw_getenv. There is only one `fw_setenv` on the system.
```
root@jetson-tx2:~# find / -name fw_setenv
/usr/bin/fw_setenv
```
`fw_setenv test_variable=1` does not work.`fw_setenv test_variable 1` works.

It looks in the deployment log like `commit` tries to use `=` for `upgrade_available`:
```
{"level":"info","message":"Committing update","timestamp":"2020-12-04T15:44:13Z"}
{"level":"info","message":"Probing the Bootloader environment for which separator to use","timestamp":"2020-12-04T15:44:13Z"}
{"level":"info","message":"Writing map[mender_uboot_separator:1] to the U-Boot environment, using separator:  ","timestamp":"2020-12-04T15:44:13Z"}
{"level":"info","message":"Writing map[upgrade_available:0] to the U-Boot environment, using separator: =","timestamp":"2020-12-04T15:44:13Z"}
```
```
root@jetson-tx2:~# fw_printenv upgrade_available
upgrade_available=1
root@jetson-tx2:~# fw_printenv mender_uboot_separator
mender_uboot_separator=
```

I used now meta-mender dunfell-v2020.11 , meta-mender-community 02ccb51 , meta-tegra 42b04e9 , poky dunfell-23.0.2 .

```
root@jetson-tx2:~# cat /data/u-boot/fw_env.config                                                                                                                                                                  
/dev/mmcblk0boot1 0x3bb000 0x20000
/dev/mmcblk0boot1 0x3db000 0x20000
root@jetson-tx2:~# ls -l /etc/fw_env.config 
lrwxrwxrwx 1 root root 26 Mar 9 2018 /etc/fw_env.config -> /data/u-boot/fw_env.config
```

**Comment by gb-g** [comment]
I think I found the problem: Mender uses `fw_setenv -f -` . This is supported starting from libubootenv 0.3, which is provided by poky dunfell-23.0.3 .

**Comment by dwalkes** [comment]
Thanks for the update @gb-g 

I'm trying to understand how we got into this situation though, are you reproducing this on https://github.com/OE4T/tegra-demo-distro/tree/dunfell-l4t-r32.4.3 ?  It seems like nothing would be working at all in this case, the problems wouldn't be limited to upgrades across distributions...

**Comment by gb-g** [comment]
No, I used poky dunfell-23.0.2 . You're right: https://github.com/OE4T/tegra-demo-distro/tree/dunfell-l4t-r32.4.3 has been using from the start a commit after the addition of libubootenv 0.3 to poky.

**Comment by dwalkes** [comment]
OK good to know.  So you expect (but haven't tested yet) that a mender update from zeus to tegra-demo-distro dunfell-l4t-r32.4.3 will work properly, is that correct?

**Comment by gb-g** [comment]
I expect that a mender update from zeus to tegra-demo-distro dunfell-l4t-r32.4.3 won't run into that fw_setenv/libubootenv problem.

**Comment by gb-g** [comment]
Update works now, using poky dunfell-23.0.4 .
